# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    cmds:
      - source ../.env
      - mix deps.get --only prod
      - MIX_ENV=prod mix compile
      - MIX_ENV=prod mix assets.deploy
  start_prod:
    deps: [build]
    cmds:
      - PORT=4001 MIX_ENV=prod iex -S mix phx.server
  release:
    deps: [build]
    cmds:
      - mix phx.gen.release # --docker 
      - MIX_ENV=prod mix release --overwrite
      - mix phx.digest.clean --all
  start_release:
    deps: [release]
    cmds:
      - PHX_SERVER=true _build/prod/rel/mkoussaelixir/bin/mkoussaelixir start
      - _build/prod/rel/mkoussaelixir/bin/mkoussaelixir remote
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
